# Generated by Django 4.2.4 on 2023-08-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeestores', '0003_coffeedrink_photo_coffeedrinker_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeedrink',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='coffeedrinker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='files'),
        ),
    ]
