# Generated by Django 4.2.4 on 2023-08-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeestores', '0004_alter_coffeedrink_photo_alter_coffeedrinker_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='descriptors',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
