# Generated by Django 4.2.4 on 2023-08-23 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffeestores', '0005_alter_review_descriptors'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coffeestores.coffeedrink'),
        ),
    ]
