# Generated by Django 4.2.4 on 2023-11-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeestores', '0006_review_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeedrinker',
            name='education',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
