# Generated by Django 4.2.4 on 2023-11-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeestores', '0007_alter_coffeedrinker_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeedrinker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
